import { Card } from "./types";

export const gachapool: Card[] = [
    { id: "1000", name: "Kaede", iml: "../assets/gachamachine/princess_kaede.webp", atk: 10, def: 10, cost: 7, special: "", description: " Kaede, the princess" },
    { id: "1001", name: "Jukebox", iml: "../assets/gachamachine/hero_boxjuke.webp", atk: 2, def: 1, cost: 2, special: "", description: " Jukebox, the music hero" },
    { id: "1002", name: "Echelon", iml: "../assets/gachamachine/hero_echelon.webp", atk: 1, def: 3, cost: 2, special: "", description: " Echelon, the physics hero" },
    { id: "1003", name: "Firisu", iml: "../assets/gachamachine/hero_firisu.webp", atk: 3, def: 2, cost: 2, special: "", description: " Firisu, the fire hero" },
    { id: "1004", name: "Shades", iml: "../assets/gachamachine/hero_shades.webp", atk: 5, def: 5, cost: 5, special: "", description: " Shades, the vision hero" },
    { id: "1005", name: "Aslo", iml: "../assets/gachamachine/ice_aslo.webp", atk: 1, def: 1, cost: 1, special: "", description: " Aslo, the ice climber" },
    { id: "1006", name: "Linkers", iml: "../assets/gachamachine/ice_linkers.webp", atk: 2, def: 2, cost: 2, special: "", description: " Linkers, the ice twins" },
    { id: "1007", name: "Makia", iml: "../assets/gachamachine/ice_makia.webp", atk: 3, def: 2, cost: 3, special: "", description: " Makia, the ice beauty" },
    { id: "1008", name: "Bou", iml: "../assets/gachamachine/jungle_bou.webp", atk: 3, def: 1, cost: 2, special: "", description: " Bou, the jungle monkey" },
    { id: "1009", name: "Topal", iml: "../assets/gachamachine/jungle_topal.webp", atk: 5, def: 6, cost: 4, special: "", description: " Topal, the jungle king" },
    { id: "1010", name: "Aror", iml: "../assets/gachamachine/midori_aror.webp", atk: 2, def: 3, cost: 2, special: "", description: " Aror, the green lion" },
    { id: "1011", name: "Grandmido", iml: "../assets/gachamachine/midori_grandmido.webp", atk: 5, def: 5, cost: 6, special: "", description: " Granmido, the green grandpa" },
    { id: "1012", name: "Gulper", iml: "../assets/gachamachine/midori_gulper.webp", atk: 1, def: 1, cost: 1, special: "", description: " Gulper, the green goblin" },
    { id: "1013", name: "Primido", iml: "../assets/gachamachine/midori_prince.webp", atk: 2, def: 1, cost: 1, special: "", description: " Primido, the green prince" },
    { id: "1014", name: "Midori", iml: "../assets/gachamachine/midori_princess.webp", atk: 1, def: 2, cost: 1, special: "", description: " Midori, the green princess" },
    { id: "1015", name: "Royalmido", iml: "../assets/gachamachine/midori_royal.webp", atk: 8, def: 6, cost: 6, special: "", description: " Royalmido, the green king" },
    { id: "1016", name: "Toy Warrior", iml: "../assets/gachamachine/toy_warrior.webp", atk: 2, def: 1, cost: 1, special: "", description: " A fighter toy reanimated" },
    { id: "1017", name: "Garru", iml: "../assets/gachamachine/underworld_garru.webp", atk: 1, def: 1, cost: 1, special: "", description: "Garru, the gargoyle" },
    { id: "1018", name: "Grandvil", iml: "../assets/gachamachine/underworld_grandvil.webp", atk: 3, def: 2, cost: 1, special: "", description: "Grandvil, the red grandpa" },
    { id: "1019", name: "Peperu", iml: "../assets/gachamachine/underworld_peperu.webp", atk: 1, def: 4, cost: 2, special: "", description: "Peperu, the red skull" },
    { id: "1020", name: "Rosevil", iml: "../assets/gachamachine/underworld_rosevil.webp", atk: 3, def: 3, cost: 3, special: "", description: "Rosevil, the seductive" },
    { id: "1021", name: "Sir Spooky", iml: "../assets/gachamachine/underworld_sirspooky.webp", atk: 1, def: 6, cost: 3, special: "", description: "Sir Spooky, the ghost guard" },
    { id: "1022", name: "Bearstone", iml: "../assets/gachamachine/wit_beardstone.webp", atk: 2, def: 2, cost: 2, special: "", description: "Bearstone, the wise" },
    { id: "1023", name: "Brook", iml: "../assets/gachamachine/wit_brook.webp", atk: 1, def: 1, cost: 1, special: "", description: "Brook, the beginner" },
    { id: "1024", name: "Guindrum", iml: "../assets/gachamachine/wit_guindrum.webp", atk: 1, def: 3, cost: 1, special: "", description: "Guindrum, the elegant" },
    { id: "1025", name: "Hawkwood", iml: "../assets/gachamachine/wit_hawkwood.webp", atk: 4, def: 4, cost: 2, special: "", description: "Hawkwood, the veteran" },
    { id: "1026", name: "Moonstone", iml: "../assets/gachamachine/wit_moonstone.webp", atk: 8, def: 9, cost: 6, special: "", description: "Moonstone, the omniscient" },
]
